-- ---------------------------------------------------------------------------
-- Schema inicial do Send Hemosc.
--
-- PROTOTIPO: este banco e alimentado exclusivamente com dados ficticios.
-- Nenhum dado real de doador ou de estoque deve ser carregado aqui.
-- ---------------------------------------------------------------------------

CREATE TABLE doador (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                VARCHAR(150)  NOT NULL,
    email               VARCHAR(180)  NOT NULL,
    telefone            VARCHAR(20),
    tipo_sanguineo      VARCHAR(3)    NOT NULL,
    sexo                VARCHAR(10)   NOT NULL,
    data_nascimento     DATE          NOT NULL,
    peso_kg             NUMERIC(5, 2),
    ativo               BOOLEAN       NOT NULL DEFAULT TRUE,
    -- LGPD: consentimento explicito para receber convocacoes
    aceita_contato      BOOLEAN       NOT NULL DEFAULT FALSE,
    token_descadastro   VARCHAR(64)   NOT NULL,
    criado_em           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_doador_email UNIQUE (email),
    CONSTRAINT uk_doador_token UNIQUE (token_descadastro)
);

CREATE INDEX idx_doador_tipo_sanguineo ON doador (tipo_sanguineo);
CREATE INDEX idx_doador_elegivel ON doador (tipo_sanguineo, ativo, aceita_contato);

CREATE TABLE doacao (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doador_id     BIGINT      NOT NULL,
    data_doacao   DATE        NOT NULL,
    local_coleta  VARCHAR(150),
    observacao    VARCHAR(500),
    criado_em     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_doacao_doador FOREIGN KEY (doador_id) REFERENCES doador (id) ON DELETE CASCADE
);

CREATE INDEX idx_doacao_doador_data ON doacao (doador_id, data_doacao DESC);

CREATE TABLE estoque_hemocomponente (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_sanguineo   VARCHAR(3)  NOT NULL,
    quantidade_bolsas INTEGER    NOT NULL DEFAULT 0,
    capacidade_alvo  INTEGER     NOT NULL,
    atualizado_em    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_estoque_tipo UNIQUE (tipo_sanguineo),
    CONSTRAINT ck_estoque_quantidade CHECK (quantidade_bolsas >= 0),
    CONSTRAINT ck_estoque_capacidade CHECK (capacidade_alvo > 0)
);

CREATE TABLE notificacao (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doador_id             BIGINT       NOT NULL,
    tipo_sanguineo_alvo   VARCHAR(3)   NOT NULL,
    nivel_estoque         VARCHAR(20)  NOT NULL,
    status                VARCHAR(20)  NOT NULL,
    origem                VARCHAR(20)  NOT NULL,
    tentativa             INTEGER      NOT NULL DEFAULT 1,
    enviada_em            TIMESTAMP,
    compareceu_em         DATE,
    erro_mensagem         VARCHAR(500),
    criado_em             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notificacao_doador FOREIGN KEY (doador_id) REFERENCES doador (id) ON DELETE CASCADE
);

CREATE INDEX idx_notificacao_doador_envio ON notificacao (doador_id, enviada_em DESC);
CREATE INDEX idx_notificacao_status ON notificacao (status, tipo_sanguineo_alvo);
