-- ---------------------------------------------------------------------------
-- Controle de acesso e registro de consentimento.
--
-- A partir daqui o sistema deixa de ser somente demonstracao: passa a ter gente
-- identificada por tras de cada disparo de convocacao, e guarda a prova do
-- consentimento de cada doador, exigida pela LGPD.
-- ---------------------------------------------------------------------------

CREATE TABLE usuario (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                VARCHAR(150) NOT NULL,
    email               VARCHAR(180) NOT NULL,
    senha_hash          VARCHAR(100) NOT NULL,
    perfil              VARCHAR(20)  NOT NULL,
    situacao            VARCHAR(20)  NOT NULL,
    -- Token usado no link de aprovacao enviado ao responsavel master
    token_aprovacao     VARCHAR(64),
    aprovado_por        BIGINT,
    aprovado_em         TIMESTAMP,
    ultimo_acesso_em    TIMESTAMP,
    criado_em           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT uk_usuario_token UNIQUE (token_aprovacao),
    CONSTRAINT fk_usuario_aprovador FOREIGN KEY (aprovado_por) REFERENCES usuario (id)
);

CREATE INDEX idx_usuario_situacao ON usuario (situacao, perfil);

-- ---------------------------------------------------------------------------
-- Prova do consentimento do doador.
--
-- Nao basta guardar que a pessoa aceitou: e preciso saber QUANDO e QUAL versao
-- do termo ela aceitou. Sem isso nao ha como demonstrar consentimento depois.
-- ---------------------------------------------------------------------------
CREATE TABLE consentimento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doador_id       BIGINT       NOT NULL,
    versao_termo    VARCHAR(20)  NOT NULL,
    aceito          BOOLEAN      NOT NULL,
    registrado_em   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    origem          VARCHAR(30)  NOT NULL,
    CONSTRAINT fk_consentimento_doador FOREIGN KEY (doador_id) REFERENCES doador (id) ON DELETE CASCADE
);

CREATE INDEX idx_consentimento_doador ON consentimento (doador_id, registrado_em DESC);

-- ---------------------------------------------------------------------------
-- Auditoria das acoes que produzem efeito fora do sistema.
-- ---------------------------------------------------------------------------
CREATE TABLE auditoria (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id    BIGINT,
    usuario_email VARCHAR(180),
    acao          VARCHAR(50)  NOT NULL,
    detalhe       VARCHAR(500),
    ocorrido_em   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_auditoria_data ON auditoria (ocorrido_em DESC);
