-- ---------------------------------------------------------------------------
-- Historico de movimentacao do estoque.
--
-- Ate aqui cada atualizacao sobrescrevia a quantidade de bolsas e o valor anterior
-- se perdia. Cada linha guarda o antes e o depois de uma alteracao, da quantidade
-- ou da capacidade alvo, com quem a fez. Guarda o e-mail, e nao o identificador,
-- pela mesma razao da auditoria: o rastro continua legivel se a conta for removida.
-- ---------------------------------------------------------------------------
CREATE TABLE movimentacao_estoque (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_sanguineo       VARCHAR(3)   NOT NULL,
    quantidade_anterior  INTEGER      NOT NULL,
    quantidade_nova      INTEGER      NOT NULL,
    capacidade_anterior  INTEGER      NOT NULL,
    capacidade_nova      INTEGER      NOT NULL,
    usuario_email        VARCHAR(180) NOT NULL,
    ocorrido_em          TIMESTAMP    NOT NULL
);

CREATE INDEX idx_movimentacao_estoque_ocorrido ON movimentacao_estoque (ocorrido_em DESC);
