-- ---------------------------------------------------------------------------
-- Recuperacao de senha e aviso agrupado de cadastros pendentes.
-- ---------------------------------------------------------------------------

-- Pedido de recuperacao de senha. Guarda o hash do token, nunca o token: quem le o banco
-- nao consegue montar o link. Cada pedido vale uma vez, ate expirar, e so o mais recente de
-- cada conta fica aberto.
CREATE TABLE recuperacao_senha (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT      NOT NULL,
    token_hash  VARCHAR(64) NOT NULL,
    criado_em   TIMESTAMP   NOT NULL,
    expira_em   TIMESTAMP   NOT NULL,
    usado_em    TIMESTAMP,
    CONSTRAINT uk_recuperacao_senha_token UNIQUE (token_hash),
    CONSTRAINT fk_recuperacao_senha_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE
);

-- Os limites de envio contam pedidos por conta e no sistema inteiro, nas ultimas 24 horas.
CREATE INDEX idx_recuperacao_senha_usuario ON recuperacao_senha (usuario_id, criado_em);
CREATE INDEX idx_recuperacao_senha_criado ON recuperacao_senha (criado_em);

-- Quando o cadastro pendente entrou num aviso aos administradores. Nulo: ainda nao avisado.
-- O aviso deixa de sair a cada cadastro e passa a sair no maximo uma vez por periodo, com
-- todos os pendentes juntos: assim o volume de e-mail nao cresce com o de cadastros.
ALTER TABLE usuario ADD COLUMN aprovacao_avisada_em TIMESTAMP;

-- Os pendentes de antes desta versao ja foram avisados um a um, no momento do cadastro.
UPDATE usuario SET aprovacao_avisada_em = criado_em WHERE situacao = 'PENDENTE';
